# Generated by Django 3.1.5 on 2021-01-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeViewer', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.TextField(default='', editable=False),
        ),
    ]
