# Generated by Django 3.1.5 on 2021-01-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeViewer', '0003_recipe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
