from .AllRecipeScraper import AllRecipesScraper
from .BettyCrokerScraper import BettyCrockerScraper
from .CookingLightScraper import CookingLightScraper
from .CooksScraper import CooksScraper
from .EatingWellScraper import EatingWellScraper
from .EpicuriousScraper import EpicuriousScraper
from .JsonScraper import JsonScraper
from .TheKitchnScraper import TheKitchnScraper
from .RecipeScraper import RecipeScraper
